version: '3'

services:
  pg:
    image: pgvector/pgvector:0.7.0-pg15
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: app
      POSTGRES_DB: dev

  pgweb:
    image: sosedoff/pgweb:latest
    ports:
      - "8081:8081"
    environment:
      - PGWEB_DATABASE_URL=postgres://app:secret@pg:5432/dev?sslmode=disable
    depends_on:
      - pg
